services:
  - type: web
    name: cc-storage-server
    env: python
    plan: free
    buildCommand: "true"
    startCommand: "python server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
